#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias vi=vim
alias vim=nvim
alias caski='brewi --cask'
alias op-signin='eval $(op signin convoyinc)'
alias awsokta-rw='awsokta prod-rw'
alias nvmops='nvm use v10.15.0'

# Completions
compinit

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

# Common Env Vars
export VISUAL=nvim

# Functions
function ws {
 cd ~/workplace/$1
}

function cws {
 cd ~/workplace/convoy/$1
}

function awsokta {
  role='prod-ro'
  if [[ -n "$1" ]] then
    role=$1
  fi
  $(aws-okta -t 12h env $role)
}

# export PATH="/usr/local/anaconda3/bin:$PATH"  # commented out by conda initialize

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /Users/kyle221b/.convoyrc

GIT_TOKEN=9ea45cbbc5f297260d4f2153edd1312f1df257d8

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/usr/local/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

